markdown_extensions:
  - toc:
      baselevel: 2
      permalink: true
  - codehilite:
      guess_lang: false

nav:
  - Home: index.md
  - Getting started: getting-started.md
  - Examples:
      - Pi Montecarlo: examples/example_pi_montecarlo.md
      - Mandelbrot: examples/example_mandelbrot.md
      - Moments in time: examples/example_mit.md

repo_name: lithops-cloud/lithops
repo_url: https://github.com/lithops-cloud/lithops

site_description: "Lithops is a multicloud library for running serverless jobs in Python."
site_name: Lithops
theme:
  name: readthedocs
  custom_dir: custom/
